In [1]:
import os
import pymysql
import pandas.io.sql as sql
import pandas as pd

connection = pymysql.connect(host='localhost',
                            user=os.getenv('CF_DB_USER', 'root'),
                            password=os.getenv('MYSQL_PASS', 'pass'),
                            db=os.getenv('CF_DB', 'testcf'),
                            charset='utf8mb4',
                            cursorclass=pymysql.cursors.DictCursor)
connection.commit()

TypeError: read_sql() missing 1 required positional argument: 'con'

In [2]:
df_prob = sql.read_sql("select * from modification where problem_id='213B'", connection)
df_user = sql.read_sql("select * from participant", connection)
df_acc = sql.read_sql("select * from acceptance", connection)

In [3]:
df_prob

,idx,user_name,problem_id,file_name,node_type,parent_type,modification_type,during_competition,block_type
0,181311090100000,pparwal12,213B,pparwal12_18131109_213.src,comment,unit,INS,0,unit
1,181449760100000,behnood,213B,behnood_18144976_213.src,decl,decl_stmt,INS,0,unit
2,181449760100001,behnood,213B,behnood_18144976_213.src,type,decl,INS,0,unit
3,181449760100002,behnood,213B,behnood_18144976_213.src,name,decl,INS,0,unit
4,181449760100003,behnood,213B,behnood_18144976_213.src,for,block,INS,0,function
5,181449760100004,behnood,213B,behnood_18144976_213.src,comment,block,INS,0,function
6,181449760100005,behnood,213B,behnood_18144976_213.src,name,name,INS,0,unit
7,181449760100006,behnood,213B,behnood_18144976_213.src,index,name,INS,0,unit
8,181449760100007,behnood,213B,behnood_18144976_213.src,decl,decl_stmt,INS,0,function
9,181449760100008,behnood,213B,behnood_18144976_213.src,control,for,INS,0,for
10,181449760100009,behnood,213B,behnood_18144976_213.src,block,for,INS,0,for
11,181449760100010,behnood,213B,behnood_18144976_213.src,expr,index,INS,0,unit
12,181449760100011,behnood,213B,behnood_18144976_213.src,type,decl,INS,0,function
13,181449760100012,behnood,213B,behnood_18144976_213.src,name,decl,INS,0,function
14,181449760100013,behnood,213B,behnood_18144976_213.src,init,decl,INS,0,function
15,181449760100014,behnood,213B,behnood_18144976_213.src,init,control,INS,0,control init
16,181449760100015,behnood,213B,behnood_18144976_213.src,condition,control,INS,0,control condition
17,181449760100016,behnood,213B,behnood_18144976_213.src,incr,control,INS,0,control incr
18,181449760100017,behnood,213B,behnood_18144976_213.src,expr_stmt,block,INS,0,for
19,181449760100018,behnood,213B,behnood_18144976_213.src,expr_stmt,block,INS,0,for
20,181449760100019,behnood,213B,behnood_18144976_213.src,comment,block,INS,0,for
21,181449760100020,behnood,213B,behnood_18144976_213.src,literal,expr,INS,0,unit
22,181449760100021,behnood,213B,behnood_18144976_213.src,expr,init,INS,0,function
23,181449760100022,behnood,213B,behnood_18144976_213.src,decl,init,INS,0,control init
24,181449760100023,behnood,213B,behnood_18144976_213.src,expr,condition,INS,0,control condition
25,181449760100024,behnood,213B,behnood_18144976_213.src,expr,incr,INS,0,control incr
26,181449760100025,behnood,213B,behnood_18144976_213.src,expr,expr_stmt,INS,0,for
27,181449760100026,behnood,213B,behnood_18144976_213.src,expr,expr_stmt,INS,0,for
28,181449760100027,behnood,213B,behnood_18144976_213.src,literal,expr,INS,0,function
29,181449760100028,behnood,213B,behnood_18144976_213.src,type,decl,INS,0,control init
...,...,...,...,...,...,...,...,...,...
4378,211615570100018,vThejas,213B,vThejas_21161557_213.src,expr,index,INS,0,for
4379,211615570100019,vThejas,213B,vThejas_21161557_213.src,literal,expr,INS,0,function
4380,211615570100020,vThejas,213B,vThejas_21161557_213.src,name,expr,INS,0,for
4381,211615570100021,vThejas,213B,vThejas_21161557_213.src,literal,argument,DEL,0,function
4382,211623290200000,vThejas,213B,vThejas_21162329_213.src,comment,block,INS,0,function
4383,211623290200001,vThejas,213B,vThejas_21162329_213.src,literal,argument,INS,0,function
4384,215138050100000,Miyukine,213B,Miyukine_21513805_213.src,if,block,INS,0,function
4385,215138050100001,Miyukine,213B,Miyukine_21513805_213.src,condition,if,INS,0,if condition
4386,215138050100002,Miyukine,213B,Miyukine_21513805_213.src,then,if,INS,0,if then
4387,215138050100003,Miyukine,213B,Miyukine_21513805_213.src,else,if,INS,0,if
4388,215138050100004,Miyukine,213B,Miyukine_21513805_213.src,expr,condition,INS,0,if condition
4389,215138050100005,Miyukine,213B,Miyukine_21513805_213.src,block,then,INS,0,if then
4390,215138050100006,Miyukine,213B,Miyukine_21513805_213.src,block,else,INS,0,else
4391,215138050100007,Miyukine,213B,Miyukine_21513805_213.src,name,expr,INS,0,if condition
4392,215138050100008,Miyukine,213B,Miyukine_21513805_213.src,operator,expr,INS,0,if condition
4393,215138050100009,Miyukine,213B,Miyukine_21513805_213.src,literal,expr,INS,0,if condition
4394,215138050100010,Miyukine,213B,Miyukine_21513805_213.src,expr_stmt,block,INS,0,if then
4395,215138050100011,Miyukine,213B,Miyukine_21513805_213.src,expr_stmt,block,MOV,0,function
4396,215138050100012,Miyukine,213B,Miyukine_21513805_213.src,expr,expr_stmt,INS,0,if then
4397,215138050100013,Miyukine,213B,Miyukine_21513805_213.src,name,expr,INS,0,if then
4398,215138050100014,Miyukine,213B,Miyukine_21513805_213.src,operator,expr,INS,0,if then
4399,215138050100015,Miyukine,213B,Miyukine_21513805_213.src,operator,expr,INS,0,if then
4400,215138050100016,Miyukine,213B,Miyukine_21513805_213.src,name,expr,INS,0,if then
4401,215138050100017,Miyukine,213B,Miyukine_21513805_213.src,operator,expr,INS,0,if then
4402,215138050100018,Miyukine,213B,Miyukine_21513805_213.src,literal,expr,INS,0,if then
4403,215138050100019,Miyukine,213B,Miyukine_21513805_213.src,operator,expr,INS,0,if then
4404,215138050100020,Miyukine,213B,Miyukine_21513805_213.src,name,expr,INS,0,if then
4405,215138050100021,Miyukine,213B,Miyukine_21513805_213.src,operator,expr,INS,0,if then
4406,215138050100022,Miyukine,213B,Miyukine_21513805_213.src,operator,expr,INS,0,if then
4407,215138050100023,Miyukine,213B,Miyukine_21513805_213.src,name,expr,INS,0,if then

In [4]:
merged = df_prob.merge(df_user).merge(df_acc)

In [5]:
merged

,idx,user_name,problem_id,file_name,node_type,parent_type,modification_type,during_competition,block_type,rating,max_rating,submission_in_sample,solved_in_sample,submission,solved,acceptance_rate,lastmodified
0,181311090100000,pparwal12,213B,pparwal12_18131109_213.src,comment,unit,INS,0,unit,1774,1882,103,38,2292,869,0.379145,2017-02-01
1,181449760100000,behnood,213B,behnood_18144976_213.src,decl,decl_stmt,INS,0,unit,1741,1848,103,38,2292,869,0.379145,2017-02-01
2,181449760100001,behnood,213B,behnood_18144976_213.src,type,decl,INS,0,unit,1741,1848,103,38,2292,869,0.379145,2017-02-01
3,181449760100002,behnood,213B,behnood_18144976_213.src,name,decl,INS,0,unit,1741,1848,103,38,2292,869,0.379145,2017-02-01
4,181449760100003,behnood,213B,behnood_18144976_213.src,for,block,INS,0,function,1741,1848,103,38,2292,869,0.379145,2017-02-01
5,181449760100004,behnood,213B,behnood_18144976_213.src,comment,block,INS,0,function,1741,1848,103,38,2292,869,0.379145,2017-02-01
6,181449760100005,behnood,213B,behnood_18144976_213.src,name,name,INS,0,unit,1741,1848,103,38,2292,869,0.379145,2017-02-01
7,181449760100006,behnood,213B,behnood_18144976_213.src,index,name,INS,0,unit,1741,1848,103,38,2292,869,0.379145,2017-02-01
8,181449760100007,behnood,213B,behnood_18144976_213.src,decl,decl_stmt,INS,0,function,1741,1848,103,38,2292,869,0.379145,2017-02-01
9,181449760100008,behnood,213B,behnood_18144976_213.src,control,for,INS,0,for,1741,1848,103,38,2292,869,0.379145,2017-02-01
10,181449760100009,behnood,213B,behnood_18144976_213.src,block,for,INS,0,for,1741,1848,103,38,2292,869,0.379145,2017-02-01
11,181449760100010,behnood,213B,behnood_18144976_213.src,expr,index,INS,0,unit,1741,1848,103,38,2292,869,0.379145,2017-02-01
12,181449760100011,behnood,213B,behnood_18144976_213.src,type,decl,INS,0,function,1741,1848,103,38,2292,869,0.379145,2017-02-01
13,181449760100012,behnood,213B,behnood_18144976_213.src,name,decl,INS,0,function,1741,1848,103,38,2292,869,0.379145,2017-02-01
14,181449760100013,behnood,213B,behnood_18144976_213.src,init,decl,INS,0,function,1741,1848,103,38,2292,869,0.379145,2017-02-01
15,181449760100014,behnood,213B,behnood_18144976_213.src,init,control,INS,0,control init,1741,1848,103,38,2292,869,0.379145,2017-02-01
16,181449760100015,behnood,213B,behnood_18144976_213.src,condition,control,INS,0,control condition,1741,1848,103,38,2292,869,0.379145,2017-02-01
17,181449760100016,behnood,213B,behnood_18144976_213.src,incr,control,INS,0,control incr,1741,1848,103,38,2292,869,0.379145,2017-02-01
18,181449760100017,behnood,213B,behnood_18144976_213.src,expr_stmt,block,INS,0,for,1741,1848,103,38,2292,869,0.379145,2017-02-01
19,181449760100018,behnood,213B,behnood_18144976_213.src,expr_stmt,block,INS,0,for,1741,1848,103,38,2292,869,0.379145,2017-02-01
20,181449760100019,behnood,213B,behnood_18144976_213.src,comment,block,INS,0,for,1741,1848,103,38,2292,869,0.379145,2017-02-01
21,181449760100020,behnood,213B,behnood_18144976_213.src,literal,expr,INS,0,unit,1741,1848,103,38,2292,869,0.379145,2017-02-01
22,181449760100021,behnood,213B,behnood_18144976_213.src,expr,init,INS,0,function,1741,1848,103,38,2292,869,0.379145,2017-02-01
23,181449760100022,behnood,213B,behnood_18144976_213.src,decl,init,INS,0,control init,1741,1848,103,38,2292,869,0.379145,2017-02-01
24,181449760100023,behnood,213B,behnood_18144976_213.src,expr,condition,INS,0,control condition,1741,1848,103,38,2292,869,0.379145,2017-02-01
25,181449760100024,behnood,213B,behnood_18144976_213.src,expr,incr,INS,0,control incr,1741,1848,103,38,2292,869,0.379145,2017-02-01
26,181449760100025,behnood,213B,behnood_18144976_213.src,expr,expr_stmt,INS,0,for,1741,1848,103,38,2292,869,0.379145,2017-02-01
27,181449760100026,behnood,213B,behnood_18144976_213.src,expr,expr_stmt,INS,0,for,1741,1848,103,38,2292,869,0.379145,2017-02-01
28,181449760100027,behnood,213B,behnood_18144976_213.src,literal,expr,INS,0,function,1741,1848,103,38,2292,869,0.379145,2017-02-01
29,181449760100028,behnood,213B,behnood_18144976_213.src,type,decl,INS,0,control init,1741,1848,103,38,2292,869,0.379145,2017-02-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4378,211615570100018,vThejas,213B,vThejas_21161557_213.src,expr,index,INS,0,for,1743,1899,103,38,2292,869,0.379145,2017-02-01
4379,211615570100019,vThejas,213B,vThejas_21161557_213.src,literal,expr,INS,0,function,1743,1899,103,38,2292,869,0.379145,2017-02-01
4380,211615570100020,vThejas,213B,vThejas_21161557_213.src,name,expr,INS,0,for,1743,1899,103,38,2292,869,0.379145,2017-02-01
4381,211615570100021,vThejas,213B,vThejas_21161557_213.src,literal,argument,DEL,0,function,1743,1899,103,38,2292,869,0.379145,2017-02-01
4382,211623290200000,vThejas,213B,vThejas_21162329_213.src,comment,block,INS,0,function,1743,1899,103,38,2292,869,0.379145,2017-02-01
4383,211623290200001,vThejas,213B,vThejas_21162329_213.src,literal,argument,INS,0,function,1743,1899,103,38,2292,869,0.379145,2017-02-01
4384,215138050100000,Miyukine,213B,Miyukine_21513805_213.src,if,block,INS,0,function,1962,2222,103,38,2292,869,0.379145,2017-02-01
4385,215138050100001,Miyukine,213B,Miyukine_21513805_213.src,condition,if,INS,0,if condition,1962,2222,103,38,2292,869,0.379145,2017-02-01
4386,215138050100002,Miyukine,213B,Miyukine_21513805_213.src,then,if,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01
4387,215138050100003,Miyukine,213B,Miyukine_21513805_213.src,else,if,INS,0,if,1962,2222,103,38,2292,869,0.379145,2017-02-01
4388,215138050100004,Miyukine,213B,Miyukine_21513805_213.src,expr,condition,INS,0,if condition,1962,2222,103,38,2292,869,0.379145,2017-02-01
4389,215138050100005,Miyukine,213B,Miyukine_21513805_213.src,block,then,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01
4390,215138050100006,Miyukine,213B,Miyukine_21513805_213.src,block,else,INS,0,else,1962,2222,103,38,2292,869,0.379145,2017-02-01
4391,215138050100007,Miyukine,213B,Miyukine_21513805_213.src,name,expr,INS,0,if condition,1962,2222,103,38,2292,869,0.379145,2017-02-01
4392,215138050100008,Miyukine,213B,Miyukine_21513805_213.src,operator,expr,INS,0,if condition,1962,2222,103,38,2292,869,0.379145,2017-02-01
4393,215138050100009,Miyukine,213B,Miyukine_21513805_213.src,literal,expr,INS,0,if condition,1962,2222,103,38,2292,869,0.379145,2017-02-01
4394,215138050100010,Miyukine,213B,Miyukine_21513805_213.src,expr_stmt,block,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01
4395,215138050100011,Miyukine,213B,Miyukine_21513805_213.src,expr_stmt,block,MOV,0,function,1962,2222,103,38,2292,869,0.379145,2017-02-01
4396,215138050100012,Miyukine,213B,Miyukine_21513805_213.src,expr,expr_stmt,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01
4397,215138050100013,Miyukine,213B,Miyukine_21513805_213.src,name,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01
4398,215138050100014,Miyukine,213B,Miyukine_21513805_213.src,operator,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01
4399,215138050100015,Miyukine,213B,Miyukine_21513805_213.src,operator,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01
4400,215138050100016,Miyukine,213B,Miyukine_21513805_213.src,name,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01
4401,215138050100017,Miyukine,213B,Miyukine_21513805_213.src,operator,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01
4402,215138050100018,Miyukine,213B,Miyukine_21513805_213.src,literal,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01
4403,215138050100019,Miyukine,213B,Miyukine_21513805_213.src,operator,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01
4404,215138050100020,Miyukine,213B,Miyukine_21513805_213.src,name,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01
4405,215138050100021,Miyukine,213B,Miyukine_21513805_213.src,operator,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01
4406,215138050100022,Miyukine,213B,Miyukine_21513805_213.src,operator,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01
4407,215138050100023,Miyukine,213B,Miyukine_21513805_213.src,name,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01

In [16]:
rating_split = [
    1100, 1200, 1300, 1400, 1500, 1600, 1700, 1900, 2200, 9999
]
rating_split_bin = [-1000] + rating_split
rating_label = ['%d - %d' % (s + 1, t) for s, t in zip(rating_split_bin, rating_split_bin[1:])]
rating_label[0] = ' - 1100'
rating_label[-1] = '2200 - '

In [17]:
rating_bin = pd.cut(merged.rating, rating_split_bin, labels=rating_label)
rating_bin

0       1701 - 1900
1       1701 - 1900
2       1701 - 1900
3       1701 - 1900
4       1701 - 1900
5       1701 - 1900
6       1701 - 1900
7       1701 - 1900
8       1701 - 1900
9       1701 - 1900
10      1701 - 1900
11      1701 - 1900
12      1701 - 1900
13      1701 - 1900
14      1701 - 1900
15      1701 - 1900
16      1701 - 1900
17      1701 - 1900
18      1701 - 1900
19      1701 - 1900
20      1701 - 1900
21      1701 - 1900
22      1701 - 1900
23      1701 - 1900
24      1701 - 1900
25      1701 - 1900
26      1701 - 1900
27      1701 - 1900
28      1701 - 1900
29      1701 - 1900
           ...
4378    1701 - 1900
4379    1701 - 1900
4380    1701 - 1900
4381    1701 - 1900
4382    1701 - 1900
4383    1701 - 1900
4384    1901 - 2200
4385    1901 - 2200
4386    1901 - 2200
4387    1901 - 2200
4388    1901 - 2200
4389    1901 - 2200
4390    1901 - 2200
4391    1901 - 2200
4392    1901 - 2200
4393    1901 - 2200
4394    1901 - 2200
4395    1901 - 2200
4396    1901 - 2200
4397    1901 - 2200
4398    1901 - 2200
4399    1901 - 2200
4400    1901 - 2200
4401    1901 - 2200
4402    1901 - 2200
4403    1901 - 2200
4404    1901 - 2200
4405    1901 - 2200
4406    1901 - 2200
4407    1901 - 2200
Name: rating, dtype: category
Categories (10, object): [- 1100 < 1101 - 1200 < 1201 - 1300 < 1301 - 1400 ... 1601 - 1700 < 1701 - 1900 < 1901 - 2200 < 2200 -]

In [18]:
merged['rating_bin'] = rating_bin
merged

,idx,user_name,problem_id,file_name,node_type,parent_type,modification_type,during_competition,block_type,rating,max_rating,submission_in_sample,solved_in_sample,submission,solved,acceptance_rate,lastmodified,rating_bin
0,181311090100000,pparwal12,213B,pparwal12_18131109_213.src,comment,unit,INS,0,unit,1774,1882,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
1,181449760100000,behnood,213B,behnood_18144976_213.src,decl,decl_stmt,INS,0,unit,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
2,181449760100001,behnood,213B,behnood_18144976_213.src,type,decl,INS,0,unit,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
3,181449760100002,behnood,213B,behnood_18144976_213.src,name,decl,INS,0,unit,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
4,181449760100003,behnood,213B,behnood_18144976_213.src,for,block,INS,0,function,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
5,181449760100004,behnood,213B,behnood_18144976_213.src,comment,block,INS,0,function,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
6,181449760100005,behnood,213B,behnood_18144976_213.src,name,name,INS,0,unit,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
7,181449760100006,behnood,213B,behnood_18144976_213.src,index,name,INS,0,unit,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
8,181449760100007,behnood,213B,behnood_18144976_213.src,decl,decl_stmt,INS,0,function,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
9,181449760100008,behnood,213B,behnood_18144976_213.src,control,for,INS,0,for,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
10,181449760100009,behnood,213B,behnood_18144976_213.src,block,for,INS,0,for,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
11,181449760100010,behnood,213B,behnood_18144976_213.src,expr,index,INS,0,unit,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
12,181449760100011,behnood,213B,behnood_18144976_213.src,type,decl,INS,0,function,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
13,181449760100012,behnood,213B,behnood_18144976_213.src,name,decl,INS,0,function,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
14,181449760100013,behnood,213B,behnood_18144976_213.src,init,decl,INS,0,function,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
15,181449760100014,behnood,213B,behnood_18144976_213.src,init,control,INS,0,control init,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
16,181449760100015,behnood,213B,behnood_18144976_213.src,condition,control,INS,0,control condition,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
17,181449760100016,behnood,213B,behnood_18144976_213.src,incr,control,INS,0,control incr,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
18,181449760100017,behnood,213B,behnood_18144976_213.src,expr_stmt,block,INS,0,for,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
19,181449760100018,behnood,213B,behnood_18144976_213.src,expr_stmt,block,INS,0,for,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
20,181449760100019,behnood,213B,behnood_18144976_213.src,comment,block,INS,0,for,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
21,181449760100020,behnood,213B,behnood_18144976_213.src,literal,expr,INS,0,unit,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
22,181449760100021,behnood,213B,behnood_18144976_213.src,expr,init,INS,0,function,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
23,181449760100022,behnood,213B,behnood_18144976_213.src,decl,init,INS,0,control init,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
24,181449760100023,behnood,213B,behnood_18144976_213.src,expr,condition,INS,0,control condition,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
25,181449760100024,behnood,213B,behnood_18144976_213.src,expr,incr,INS,0,control incr,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
26,181449760100025,behnood,213B,behnood_18144976_213.src,expr,expr_stmt,INS,0,for,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
27,181449760100026,behnood,213B,behnood_18144976_213.src,expr,expr_stmt,INS,0,for,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
28,181449760100027,behnood,213B,behnood_18144976_213.src,literal,expr,INS,0,function,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
29,181449760100028,behnood,213B,behnood_18144976_213.src,type,decl,INS,0,control init,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4378,211615570100018,vThejas,213B,vThejas_21161557_213.src,expr,index,INS,0,for,1743,1899,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
4379,211615570100019,vThejas,213B,vThejas_21161557_213.src,literal,expr,INS,0,function,1743,1899,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
4380,211615570100020,vThejas,213B,vThejas_21161557_213.src,name,expr,INS,0,for,1743,1899,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
4381,211615570100021,vThejas,213B,vThejas_21161557_213.src,literal,argument,DEL,0,function,1743,1899,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
4382,211623290200000,vThejas,213B,vThejas_21162329_213.src,comment,block,INS,0,function,1743,1899,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
4383,211623290200001,vThejas,213B,vThejas_21162329_213.src,literal,argument,INS,0,function,1743,1899,103,38,2292,869,0.379145,2017-02-01,1701 - 1900
4384,215138050100000,Miyukine,213B,Miyukine_21513805_213.src,if,block,INS,0,function,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200
4385,215138050100001,Miyukine,213B,Miyukine_21513805_213.src,condition,if,INS,0,if condition,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200
4386,215138050100002,Miyukine,213B,Miyukine_21513805_213.src,then,if,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200
4387,215138050100003,Miyukine,213B,Miyukine_21513805_213.src,else,if,INS,0,if,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200
4388,215138050100004,Miyukine,213B,Miyukine_21513805_213.src,expr,condition,INS,0,if condition,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200
4389,215138050100005,Miyukine,213B,Miyukine_21513805_213.src,block,then,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200
4390,215138050100006,Miyukine,213B,Miyukine_21513805_213.src,block,else,INS,0,else,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200
4391,215138050100007,Miyukine,213B,Miyukine_21513805_213.src,name,expr,INS,0,if condition,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200
4392,215138050100008,Miyukine,213B,Miyukine_21513805_213.src,operator,expr,INS,0,if condition,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200
4393,215138050100009,Miyukine,213B,Miyukine_21513805_213.src,literal,expr,INS,0,if condition,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200
4394,215138050100010,Miyukine,213B,Miyukine_21513805_213.src,expr_stmt,block,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200
4395,215138050100011,Miyukine,213B,Miyukine_21513805_213.src,expr_stmt,block,MOV,0,function,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200
4396,215138050100012,Miyukine,213B,Miyukine_21513805_213.src,expr,expr_stmt,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200
4397,215138050100013,Miyukine,213B,Miyukine_21513805_213.src,name,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200
4398,215138050100014,Miyukine,213B,Miyukine_21513805_213.src,operator,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200
4399,215138050100015,Miyukine,213B,Miyukine_21513805_213.src,operator,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200
4400,215138050100016,Miyukine,213B,Miyukine_21513805_213.src,name,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200
4401,215138050100017,Miyukine,213B,Miyukine_21513805_213.src,operator,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200
4402,215138050100018,Miyukine,213B,Miyukine_21513805_213.src,literal,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200
4403,215138050100019,Miyukine,213B,Miyukine_21513805_213.src,operator,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200
4404,215138050100020,Miyukine,213B,Miyukine_21513805_213.src,name,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200
4405,215138050100021,Miyukine,213B,Miyukine_21513805_213.src,operator,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200
4406,215138050100022,Miyukine,213B,Miyukine_21513805_213.src,operator,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200
4407,215138050100023,Miyukine,213B,Miyukine_21513805_213.src,name,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200

In [19]:
acceptance_split = [0.2 * i for i in range(6)]
merged['acceptance_bin'] = pd.cut(merged.acceptance_rate, acceptance_split)
merged

,idx,user_name,problem_id,file_name,node_type,parent_type,modification_type,during_competition,block_type,rating,max_rating,submission_in_sample,solved_in_sample,submission,solved,acceptance_rate,lastmodified,rating_bin,acceptance_bin
0,181311090100000,pparwal12,213B,pparwal12_18131109_213.src,comment,unit,INS,0,unit,1774,1882,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
1,181449760100000,behnood,213B,behnood_18144976_213.src,decl,decl_stmt,INS,0,unit,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
2,181449760100001,behnood,213B,behnood_18144976_213.src,type,decl,INS,0,unit,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
3,181449760100002,behnood,213B,behnood_18144976_213.src,name,decl,INS,0,unit,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
4,181449760100003,behnood,213B,behnood_18144976_213.src,for,block,INS,0,function,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
5,181449760100004,behnood,213B,behnood_18144976_213.src,comment,block,INS,0,function,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
6,181449760100005,behnood,213B,behnood_18144976_213.src,name,name,INS,0,unit,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
7,181449760100006,behnood,213B,behnood_18144976_213.src,index,name,INS,0,unit,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
8,181449760100007,behnood,213B,behnood_18144976_213.src,decl,decl_stmt,INS,0,function,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
9,181449760100008,behnood,213B,behnood_18144976_213.src,control,for,INS,0,for,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
10,181449760100009,behnood,213B,behnood_18144976_213.src,block,for,INS,0,for,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
11,181449760100010,behnood,213B,behnood_18144976_213.src,expr,index,INS,0,unit,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
12,181449760100011,behnood,213B,behnood_18144976_213.src,type,decl,INS,0,function,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
13,181449760100012,behnood,213B,behnood_18144976_213.src,name,decl,INS,0,function,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
14,181449760100013,behnood,213B,behnood_18144976_213.src,init,decl,INS,0,function,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
15,181449760100014,behnood,213B,behnood_18144976_213.src,init,control,INS,0,control init,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
16,181449760100015,behnood,213B,behnood_18144976_213.src,condition,control,INS,0,control condition,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
17,181449760100016,behnood,213B,behnood_18144976_213.src,incr,control,INS,0,control incr,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
18,181449760100017,behnood,213B,behnood_18144976_213.src,expr_stmt,block,INS,0,for,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
19,181449760100018,behnood,213B,behnood_18144976_213.src,expr_stmt,block,INS,0,for,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
20,181449760100019,behnood,213B,behnood_18144976_213.src,comment,block,INS,0,for,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
21,181449760100020,behnood,213B,behnood_18144976_213.src,literal,expr,INS,0,unit,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
22,181449760100021,behnood,213B,behnood_18144976_213.src,expr,init,INS,0,function,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
23,181449760100022,behnood,213B,behnood_18144976_213.src,decl,init,INS,0,control init,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
24,181449760100023,behnood,213B,behnood_18144976_213.src,expr,condition,INS,0,control condition,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
25,181449760100024,behnood,213B,behnood_18144976_213.src,expr,incr,INS,0,control incr,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
26,181449760100025,behnood,213B,behnood_18144976_213.src,expr,expr_stmt,INS,0,for,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
27,181449760100026,behnood,213B,behnood_18144976_213.src,expr,expr_stmt,INS,0,for,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
28,181449760100027,behnood,213B,behnood_18144976_213.src,literal,expr,INS,0,function,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
29,181449760100028,behnood,213B,behnood_18144976_213.src,type,decl,INS,0,control init,1741,1848,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4378,211615570100018,vThejas,213B,vThejas_21161557_213.src,expr,index,INS,0,for,1743,1899,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
4379,211615570100019,vThejas,213B,vThejas_21161557_213.src,literal,expr,INS,0,function,1743,1899,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
4380,211615570100020,vThejas,213B,vThejas_21161557_213.src,name,expr,INS,0,for,1743,1899,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
4381,211615570100021,vThejas,213B,vThejas_21161557_213.src,literal,argument,DEL,0,function,1743,1899,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
4382,211623290200000,vThejas,213B,vThejas_21162329_213.src,comment,block,INS,0,function,1743,1899,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
4383,211623290200001,vThejas,213B,vThejas_21162329_213.src,literal,argument,INS,0,function,1743,1899,103,38,2292,869,0.379145,2017-02-01,1701 - 1900,"(0.2, 0.4]"
4384,215138050100000,Miyukine,213B,Miyukine_21513805_213.src,if,block,INS,0,function,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200,"(0.2, 0.4]"
4385,215138050100001,Miyukine,213B,Miyukine_21513805_213.src,condition,if,INS,0,if condition,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200,"(0.2, 0.4]"
4386,215138050100002,Miyukine,213B,Miyukine_21513805_213.src,then,if,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200,"(0.2, 0.4]"
4387,215138050100003,Miyukine,213B,Miyukine_21513805_213.src,else,if,INS,0,if,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200,"(0.2, 0.4]"
4388,215138050100004,Miyukine,213B,Miyukine_21513805_213.src,expr,condition,INS,0,if condition,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200,"(0.2, 0.4]"
4389,215138050100005,Miyukine,213B,Miyukine_21513805_213.src,block,then,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200,"(0.2, 0.4]"
4390,215138050100006,Miyukine,213B,Miyukine_21513805_213.src,block,else,INS,0,else,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200,"(0.2, 0.4]"
4391,215138050100007,Miyukine,213B,Miyukine_21513805_213.src,name,expr,INS,0,if condition,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200,"(0.2, 0.4]"
4392,215138050100008,Miyukine,213B,Miyukine_21513805_213.src,operator,expr,INS,0,if condition,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200,"(0.2, 0.4]"
4393,215138050100009,Miyukine,213B,Miyukine_21513805_213.src,literal,expr,INS,0,if condition,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200,"(0.2, 0.4]"
4394,215138050100010,Miyukine,213B,Miyukine_21513805_213.src,expr_stmt,block,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200,"(0.2, 0.4]"
4395,215138050100011,Miyukine,213B,Miyukine_21513805_213.src,expr_stmt,block,MOV,0,function,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200,"(0.2, 0.4]"
4396,215138050100012,Miyukine,213B,Miyukine_21513805_213.src,expr,expr_stmt,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200,"(0.2, 0.4]"
4397,215138050100013,Miyukine,213B,Miyukine_21513805_213.src,name,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200,"(0.2, 0.4]"
4398,215138050100014,Miyukine,213B,Miyukine_21513805_213.src,operator,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200,"(0.2, 0.4]"
4399,215138050100015,Miyukine,213B,Miyukine_21513805_213.src,operator,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200,"(0.2, 0.4]"
4400,215138050100016,Miyukine,213B,Miyukine_21513805_213.src,name,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200,"(0.2, 0.4]"
4401,215138050100017,Miyukine,213B,Miyukine_21513805_213.src,operator,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200,"(0.2, 0.4]"
4402,215138050100018,Miyukine,213B,Miyukine_21513805_213.src,literal,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200,"(0.2, 0.4]"
4403,215138050100019,Miyukine,213B,Miyukine_21513805_213.src,operator,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200,"(0.2, 0.4]"
4404,215138050100020,Miyukine,213B,Miyukine_21513805_213.src,name,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200,"(0.2, 0.4]"
4405,215138050100021,Miyukine,213B,Miyukine_21513805_213.src,operator,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200,"(0.2, 0.4]"
4406,215138050100022,Miyukine,213B,Miyukine_21513805_213.src,operator,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200,"(0.2, 0.4]"
4407,215138050100023,Miyukine,213B,Miyukine_21513805_213.src,name,expr,INS,0,if then,1962,2222,103,38,2292,869,0.379145,2017-02-01,1901 - 2200,"(0.2, 0.4]"

In [33]:
grouped = merged.groupby(['block_type', 'node_type', 'modification_type', 'rating_bin']).size()
grouped

block_type         node_type      modification_type  rating_bin
control condition  argument_list  DEL                1901 - 2200     1
                   call           DEL                1901 - 2200     1
                   condition      DEL                1301 - 1400     8
                                                     1401 - 1500    11
                                                     1501 - 1600     1
                                                     1901 - 2200     3
                                  INS                1401 - 1500    12
                                                     1501 - 1600     2
                                                     1701 - 1900     1
                                                     1901 - 2200     4
                   expr           DEL                1301 - 1400     6
                                                     1401 - 1500    11
                                                     1501 - 1600     1
                                                     1901 - 2200     2
                                  INS                1401 - 1500    12
                                                     1501 - 1600     2
                                                     1701 - 1900     2
                                                     1901 - 2200     3
                                  MOV                1301 - 1400     2
                                                     1901 - 2200     1
                   index          INS                1701 - 1900     1
                   literal        DEL                1301 - 1400     1
                                                     1401 - 1500     4
                                                     1501 - 1600     1
                                                     1901 - 2200     4
                                  INS                1301 - 1400     2
                                                     1401 - 1500     2
                                                     1501 - 1600     2
                                                     1701 - 1900     1
                                                     1901 - 2200     2
                                                                    ..
unit               type           INS                1401 - 1500    17
                                                     1501 - 1600     2
                                                     1701 - 1900     2
                                  MOV                1401 - 1500     2
                   typedef        DEL                1401 - 1500     1
                                  INS                1401 - 1500     2
                   value          DEL                1401 - 1500     7
                                  INS                1401 - 1500     7
while              argument       DEL                1901 - 2200     5
                   argument_list  DEL                1901 - 2200     3
                   block          DEL                1901 - 2200     1
                                  INS                1901 - 2200     1
                   call           DEL                1901 - 2200     1
                   decl           DEL                1901 - 2200     1
                   decl_stmt      DEL                1901 - 2200     1
                   expr           DEL                1901 - 2200     8
                                  INS                1901 - 2200     2
                   expr_stmt      DEL                1901 - 2200     1
                                  INS                1901 - 2200     2
                                  MOV                1901 - 2200     1
                   for            DEL                1901 - 2200     1
                   index          DEL                1901 - 2200     1
                   name           DEL                1901 - 2200    14
                   operator       DEL                1901 - 2200     1
                   type           DEL                1901 - 2200     1
while condition    condition      DEL                1901 - 2200     1
                                  INS                1901 - 2200     1
                   expr           DEL                1901 - 2200     1
                   name           DEL                1901 - 2200     1
                   operator       DEL                1901 - 2200     1
dtype: int64

In [26]:
prob_info = merged.groupby(['rating_bin']).file_name.agg(lambda x: x.nunique())
prob_info

rating_bin
 - 1100         0
1101 - 1200     0
1201 - 1300     0
1301 - 1400     2
1401 - 1500    11
1501 - 1600     6
1601 - 1700     3
1701 - 1900    17
1901 - 2200    11
2200 -          0
Name: file_name, dtype: int64

In [27]:
prob_info = merged.groupby(['rating_bin']).user_name.agg(lambda x: x.nunique())
prob_info

rating_bin
 - 1100         0
1101 - 1200     0
1201 - 1300     0
1301 - 1400     2
1401 - 1500     1
1501 - 1600     2
1601 - 1700     3
1701 - 1900    10
1901 - 2200     5
2200 -          0
Name: user_name, dtype: int64

In [30]:
df_par = pd.DataFrame([[1, 0], [3, 5]])
sr_chl = pd.Series([3, 0])

In [32]:
(df_par / sr_chl).fillna(0)

          0         1
0  0.333333  0.000000
1  1.000000       inf

In [34]:
grouped / prob_info

block_type         node_type      modification_type  rating_bin
control condition  argument_list  DEL                1901 - 2200     0.2
                   call           DEL                1901 - 2200     0.2
                   condition      DEL                1301 - 1400     4.0
                                                     1401 - 1500    11.0
                                                     1501 - 1600     0.5
                                                     1901 - 2200     0.6
                                  INS                1401 - 1500    12.0
                                                     1501 - 1600     1.0
                                                     1701 - 1900     0.1
                                                     1901 - 2200     0.8
                   expr           DEL                1301 - 1400     3.0
                                                     1401 - 1500    11.0
                                                     1501 - 1600     0.5
                                                     1901 - 2200     0.4
                                  INS                1401 - 1500    12.0
                                                     1501 - 1600     1.0
                                                     1701 - 1900     0.2
                                                     1901 - 2200     0.6
                                  MOV                1301 - 1400     1.0
                                                     1901 - 2200     0.2
                   index          INS                1701 - 1900     0.1
                   literal        DEL                1301 - 1400     0.5
                                                     1401 - 1500     4.0
                                                     1501 - 1600     0.5
                                                     1901 - 2200     0.8
                                  INS                1301 - 1400     1.0
                                                     1401 - 1500     2.0
                                                     1501 - 1600     1.0
                                                     1701 - 1900     0.1
                                                     1901 - 2200     0.4
                                                                    ...
unit               type           INS                1401 - 1500    17.0
                                                     1501 - 1600     1.0
                                                     1701 - 1900     0.2
                                  MOV                1401 - 1500     2.0
                   typedef        DEL                1401 - 1500     1.0
                                  INS                1401 - 1500     2.0
                   value          DEL                1401 - 1500     7.0
                                  INS                1401 - 1500     7.0
while              argument       DEL                1901 - 2200     1.0
                   argument_list  DEL                1901 - 2200     0.6
                   block          DEL                1901 - 2200     0.2
                                  INS                1901 - 2200     0.2
                   call           DEL                1901 - 2200     0.2
                   decl           DEL                1901 - 2200     0.2
                   decl_stmt      DEL                1901 - 2200     0.2
                   expr           DEL                1901 - 2200     1.6
                                  INS                1901 - 2200     0.4
                   expr_stmt      DEL                1901 - 2200     0.2
                                  INS                1901 - 2200     0.4
                                  MOV                1901 - 2200     0.2
                   for            DEL                1901 - 2200     0.2
                   index          DEL                1901 - 2200     0.2
                   name           DEL                1901 - 2200     2.8
                   operator       DEL                1901 - 2200     0.2
                   type           DEL                1901 - 2200     0.2
while condition    condition      DEL                1901 - 2200     0.2
                                  INS                1901 - 2200     0.2
                   expr           DEL                1901 - 2200     0.2
                   name           DEL                1901 - 2200     0.2
                   operator       DEL                1901 - 2200     0.2
dtype: float64